In [1]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression

In [4]:
import pandas as pd
import numpy as np

# Read the CSV file and select specific columns
df = pd.read_csv('50_Startups.csv')[['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']]

# Scale the data by dividing by 10,000 and round to the nearest whole number
df = np.round(df / 10000)

# Set the random seed for reproducibility
np.random.seed(9)

In [5]:
df.head()

   R&D Spend  Administration  Marketing Spend  Profit
0       17.0            14.0             47.0    19.0
1       16.0            15.0             44.0    19.0
2       15.0            10.0             41.0    19.0
3       14.0            12.0             38.0    18.0
4       14.0             9.0             37.0    17.0

In [6]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
0        17.0            14.0             47.0
1        16.0            15.0             44.0
2        15.0            10.0             41.0
3        14.0            12.0             38.0
4        14.0             9.0             37.0
5        13.0            10.0             36.0
6        13.0            15.0             13.0
7        13.0            15.0             32.0
8        12.0            15.0             31.0
9        12.0            11.0             30.0
10       10.0            11.0             23.0
11       10.0             9.0             25.0
12        9.0            13.0             25.0
13        9.0            14.0             25.0
14       12.0            16.0             26.0
15       11.0            12.0             26.0
16        8.0            12.0             26.0
17        9.0            15.0             28.0
18        9.0            11.0             29.0
19        9.0            15.0              0.0
20        8.0            11.0             30.0
21        8.0            15.0             30.0
22        7.0            12.0             30.0
23        7.0            11.0             30.0
24        8.0            10.0             14.0
25        6.0            14.0             14.0
26        8.0            14.0             13.0
27        7.0            13.0             35.0
28        7.0            18.0             12.0
29        7.0            15.0             11.0
30        6.0            12.0              9.0
31        6.0            15.0              9.0
32        6.0            13.0              5.0
33        6.0            10.0             21.0
34        5.0            16.0             21.0
35        5.0             9.0             21.0
36        3.0            13.0             20.0
37        4.0             5.0             20.0
38        2.0             7.0             19.0
39        4.0             8.0             17.0
40        3.0            12.0             17.0
41        3.0             8.0             16.0
42        2.0            10.0             15.0
43        2.0            13.0              4.0
44        2.0            15.0              3.0
45        0.0            12.0              0.0
46        0.0            12.0             30.0
47        0.0            14.0              0.0
48        0.0             5.0              0.0
49        0.0            12.0              5.0

In [7]:
df.shape

(50, 3)

In [8]:
#  to make some values as NaN
df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,-1] = np.NaN

In [9]:
df

    R&D Spend  Administration  Marketing Spend
0        17.0            14.0             47.0
1         NaN            15.0             44.0
2        15.0            10.0             41.0
3        14.0             NaN             38.0
4        14.0             9.0             37.0
5        13.0            10.0             36.0
6        13.0            15.0             13.0
7        13.0            15.0             32.0
8        12.0            15.0             31.0
9        12.0            11.0             30.0
10       10.0            11.0             23.0
11       10.0             9.0             25.0
12        9.0            13.0             25.0
13        9.0            14.0             25.0
14       12.0            16.0             26.0
15       11.0            12.0             26.0
16        8.0            12.0             26.0
17        9.0            15.0             28.0
18        9.0            11.0             29.0
19        9.0            15.0              0.0
20        8.0            11.0             30.0
21        8.0            15.0             30.0
22        7.0            12.0             30.0
23        7.0            11.0             30.0
24        8.0            10.0             14.0
25        6.0            14.0             14.0
26        8.0            14.0             13.0
27        7.0            13.0             35.0
28        7.0            18.0             12.0
29        7.0            15.0             11.0
30        6.0            12.0              9.0
31        6.0            15.0              9.0
32        6.0            13.0              5.0
33        6.0            10.0             21.0
34        5.0            16.0             21.0
35        5.0             9.0             21.0
36        3.0            13.0             20.0
37        4.0             5.0             20.0
38        2.0             7.0             19.0
39        4.0             8.0             17.0
40        3.0            12.0             17.0
41        3.0             8.0             16.0
42        2.0            10.0             15.0
43        2.0            13.0              4.0
44        2.0            15.0              3.0
45        0.0            12.0              0.0
46        0.0            12.0             30.0
47        0.0            14.0              0.0
48        0.0             5.0              0.0
49        0.0            12.0              NaN